project:
  type: book
  title: "Statistical Computing"
  output-dir: _site  


website:
  sidebar:
    border: true
    background: light
    position: left
    collapse-level: 2
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/LBNSTE002

book:
  chapters:
    - index.qmd
    - Assignmnent 2.qmd

format:
  html:
    theme: flatly  # Clean and professional look
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: true
    code-fold: true  # Allows users to toggle code blocks
    code-overflow: wrap  # Prevents horizontal scrolling
    css: styles.css  # Custom styles if needed
